export const exerciseTemplates = [
  'Clarity',
  'Pronunciation',
  'Word swap',
  'Association',
  'Commas',
  'Diction',
  'Precision',
  'Eloquence',
  'Synonyms',
  'Recall',
  'Transitions',
  'Agility',
  'Comprehension',
  'Connotation',
  'Expression',
  'Detail',
  'Brevity',
  'Word parts',
  'Visualization',
  'Processing',
  'Extraction',
  'Inversion',
  'Punctuation',
  'Refinement',
  'Spelling',
  'Syntax',
] as const
export type ExerciseTemplateName = (typeof exerciseTemplates)[number]
export const icons: Record<ExerciseTemplateName, string> = {
  Pronunciation: 'emojione-monotone:speaking-head',
  Clarity: 'ph:list-magnifying-glass-bold',
  'Word swap': 'ic:round-swap-horiz',
  Association: 'material-symbols-light:chrome-reader-mode',
  Commas: 'simple-icons:comma',
  Diction: 'material-symbols-light:dictionary',
  Precision: 'iconoir:microphone-speaking',
  Transitions: 'material-symbols-light:transition-push',
  Eloquence: 'fluent:person-chat-16-filled',
  Detail: 'lets-icons:chat-alt',
  Processing: 'icon-park-outline:reverse-rotation',
  Comprehension: 'jam:write-f',
  Visualization: 'mdi:head-thinking',
  Agility: 'fluent:text-abc-underline-double-32-filled',
  Spelling: 'carbon:spell-check',
  Synonyms: 'icon-park:list-alphabet',
  Syntax: 'solar:list-cross-minimalistic-linear',
  Refinement: 'mdi:page-next-outline',
  Punctuation: 'fad:digital-colon',
  Extraction: 'codicon:word-wrap',
  Brevity: 'lucide:whole-word',
  'Word parts': 'gravity-ui:files',
  Connotation: 'gridicons:reader-following', // Corrected typo from "Connatation" to "Connotation"
  Expression: 'f7:square-righthalf-fill',
  Inversion: 'f7:square-lefthalf-fill',
  Recall: 'uil:files-landscapes-alt',
}
export const colors: Record<ExerciseTemplateName, [string, string]> = {
  Clarity: ['#51C9A8', '#259A7A'],
  Pronunciation: ['#FF7380', '#F83043'],
  'Word swap': ['#DE5900', '#FFAA71'],
  Association: ['#BA90FF', '#9F72E8'],
  Commas: ['#FDDF93', '#DCA925'],
  Diction: ['#009488', '#01ADAA'],
  Precision: ['#6CC5CB', '#06969E'],
  Eloquence: ['#FF9551', '#FEC26A'],
  Synonyms: ['#6CB444', '#B9F896'],
  Recall: ['#C158BD', '#CC8FED'],
  Transitions: ['#588FC7', '#7DB3EA'],
  Agility: ['#947ED4', '#9A81E6'],
  Comprehension: ['#008ABB', '#95CADC'],
  Connotation: ['#93286E', '#CA80B0'],
  Extraction: ['#C7D062', '#F2E269'],
  Processing: ['#F48983', '#F6BCB9'],
  Visualization: ['#EA5C8A', '#F7AABE'],
  'Word parts': ['#DE5900', '#FFAA71'],
  Syntax: ['#FDDF93', '#DCA925'],
  Spelling: ['#BA90FF', '#8A62CC'],
  Brevity: ['#014B7A', '#71B9E6'],
  Refinement: ['#259A7A', '#51C9A8'],
  Detail: ['#1E9949', '#5CDA88'],
  Punctuation: ['#F83043', '#FF7380'],
  Expression: ['#5E4AA4', '#9678EF'],
  Inversion: ['#E60A78', '#EC7BB3'],
}
